In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.svm import SVC
import time
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score

In [5]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape, train_labels.shape)
print(test_images.shape, test_labels.shape)

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [6]:
train_images_flat = train_images.reshape(train_images.shape[0], -1)
test_images_flat = test_images.reshape(test_images.shape[0], -1)
print(train_images_flat.shape, train_labels.shape)
print(test_images_flat.shape, test_labels.shape)

(60000, 784) (60000,)
(10000, 784) (10000,)


In [7]:
max_iter = 200

**Linear Kernel**

In [8]:
svm_linear_hard = SVC(kernel='linear', C = 1e5, max_iter = max_iter)
svm_linear_hard = svm_linear_hard.fit(train_images_flat, train_labels)
y_pred_linear_hard = svm_linear_hard.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_linear_hard))
print("\n\nPrecision:", precision_score(test_labels, y_pred_linear_hard, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_linear_hard, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_linear_hard))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.728


Precision: 0.7310662249369089


Recall: 0.7291703744438485


Confusion Matrix:
 [[933   0   1   1   1  26  14   1   2   1]
 [  0 712  67  19   1   2   2   9 319   4]
 [ 25  63 784  71  21  10  12  14  29   3]
 [ 10  41  27 775   1  98   0  12  32  14]
 [  1   2  42   6 861   2  11   5   4  48]
 [ 21  27  17 136  28 566  30   1  56  10]
 [ 28   2  55   0  36  24 811   0   2   0]
 [  4   9  19  19  26   2   0 831   8 110]
 [ 11  90  60 100  12  66  27   5 592  11]
 [  8  11  18  24 357  11   1 146  18 415]]


In [9]:
svm_linear_soft = SVC(kernel='linear', C = 10, max_iter = max_iter)
svm_linear_soft = svm_linear_soft.fit(train_images_flat, train_labels)
y_pred_linear_soft = svm_linear_soft.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_linear_soft))
print("\n\nPrecision:", precision_score(test_labels, y_pred_linear_soft, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_linear_soft, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_linear_soft))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.728


Precision: 0.7310662249369089


Recall: 0.7291703744438485


Confusion Matrix:
 [[933   0   1   1   1  26  14   1   2   1]
 [  0 712  67  19   1   2   2   9 319   4]
 [ 25  63 784  71  21  10  12  14  29   3]
 [ 10  41  27 775   1  98   0  12  32  14]
 [  1   2  42   6 861   2  11   5   4  48]
 [ 21  27  17 136  28 566  30   1  56  10]
 [ 28   2  55   0  36  24 811   0   2   0]
 [  4   9  19  19  26   2   0 831   8 110]
 [ 11  90  60 100  12  66  27   5 592  11]
 [  8  11  18  24 357  11   1 146  18 415]]


**RBF Kernel**

In [10]:
svm_rbf_hard = SVC(kernel='rbf', C = 1e5, max_iter = max_iter)
svm_rbf_hard = svm_rbf_hard.fit(train_images_flat, train_labels)
y_pred_rbf_hard = svm_rbf_hard.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_rbf_hard))
print("\n\nPrecision:", precision_score(test_labels, y_pred_rbf_hard, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_rbf_hard, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_rbf_hard))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.9792


Precision: 0.9791459925126809


Recall: 0.9789224593760977


Confusion Matrix:
 [[ 975    0    1    1    0    1    0    1    1    0]
 [   0 1131    1    0    0    1    0    1    1    0]
 [   5    1 1014    0    2    0    1    4    4    1]
 [   0    0    4  989    0    6    0    3    6    2]
 [   1    0    3    0  965    0    2    1    1    9]
 [   2    0    0   16    2  864    3    0    4    1]
 [   5    2    0    0    2    4  944    0    1    0]
 [   0    5    8    2    4    0    0  997    0   12]
 [   3    0    3   12    1    3    2    2  944    4]
 [   3    4    0    8   13    2    0    3    7  969]]


In [11]:
svm_rbf_soft = SVC(kernel='rbf', C = 10, max_iter = max_iter)
svm_rbf_soft = svm_rbf_soft.fit(train_images_flat, train_labels)
y_pred_rbf_sof = svm_rbf_soft.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_rbf_sof))
print("\n\nPrecision:", precision_score(test_labels, y_pred_rbf_sof, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_rbf_sof, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_rbf_sof))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.9789


Precision: 0.9788793512255225


Recall: 0.9786257770562802


Confusion Matrix:
 [[ 975    0    1    1    0    1    0    1    1    0]
 [   0 1131    1    0    0    1    0    1    1    0]
 [   5    1 1014    0    1    0    1    4    5    1]
 [   0    0    3  991    0    6    0    2    6    2]
 [   1    0    3    0  963    0    2    0    1   12]
 [   2    0    0   16    2  863    4    0    4    1]
 [   4    2    0    0    2    2  947    0    1    0]
 [   0    4    7    5    1    0    0  999    0   12]
 [   3    0    3   11    1    3    2    3  946    2]
 [   4    4    0    9   14    1    0   10    7  960]]


**Poly Kernel**

In [12]:
svm_poly_hard = SVC(kernel='poly', C = 1e5, max_iter = max_iter)
svm_poly_hard = svm_poly_hard.fit(train_images_flat, train_labels)
y_pred_poly_hard = svm_poly_hard.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_poly_hard))
print("\n\nPrecision:", precision_score(test_labels, y_pred_poly_hard, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_poly_hard, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_poly_hard))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.9677


Precision: 0.9677843117319564


Recall: 0.9673329122960623


Confusion Matrix:
 [[ 973    0    1    1    0    2    1    0    2    0]
 [   0 1127    3    1    0    0    3    1    0    0]
 [   8    2 1002    0    2    0    3    9    6    0]
 [   0    2    6  978    0   11    0    4    7    2]
 [   3    0    5    0  961    0    2    1    0   10]
 [   6    0    1   25    1  849    4    1    2    3]
 [   4    5    2    0    2    9  935    0    1    0]
 [   0   17   10    3    3    0    0  980    0   15]
 [   8    0    3   13    2    5    1    5  934    3]
 [   9    5    3    9   26    3    0   13    3  938]]


In [13]:
svm_poly_soft = SVC(kernel='poly', C = 10, max_iter = max_iter)
svm_poly_soft = svm_poly_soft.fit(train_images_flat, train_labels)
y_pred_poly_sof = svm_poly_soft.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_poly_sof))
print("\n\nPrecision:", precision_score(test_labels, y_pred_poly_sof, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_poly_sof, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_poly_sof))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.9695


Precision: 0.9693818267718057


Recall: 0.9691678692879859


Confusion Matrix:
 [[ 972    0    1    1    0    3    1    0    2    0]
 [   0 1126    3    0    0    0    4    0    2    0]
 [   8    3  998    2    2    0    4    8    6    1]
 [   1    1    7  977    0    8    0    5    8    3]
 [   2    0    2    0  955    0    2    1    0   20]
 [   2    0    2   22    1  855    4    1    3    2]
 [   4    4    1    0    1    8  939    0    1    0]
 [   0    8   12    2    3    0    0  993    0   10]
 [  10    0    4   14    2    7    1    5  927    4]
 [   7    4    2    6   27    3    0    3    4  953]]


**Sigmoid Kernel**

In [14]:
svm_sigmoid_hard = SVC(kernel='sigmoid', C = 1e5, max_iter = max_iter)
svm_sigmoid_hard = svm_sigmoid_hard.fit(train_images_flat, train_labels)
y_pred_sigmoid_hard = svm_sigmoid_hard.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_sigmoid_hard))
print("\n\nPrecision:", precision_score(test_labels, y_pred_sigmoid_hard, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_sigmoid_hard, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_sigmoid_hard))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.5602


Precision: 0.6232899609826216


Recall: 0.5558774184537899


Confusion Matrix:
 [[ 762    0   10    2    1   27   63    0  107    8]
 [   1 1017   32   16    0    2    4    0   61    2]
 [  46   81  218   44   13    5  175   12  405   33]
 [  54   22   17  436    1  146   16   15  253   50]
 [   2    4   11    4  295    1   29    5   38  593]
 [  85   24    7   77   15  300   29    8  295   52]
 [  31    7   67   10   24    9  768    0   37    5]
 [   5   15   27    8    3    0    1  359   47  563]
 [  49   64   37   48    7   44   23    8  577  117]
 [  16    6    5    4   31   11    0   31   35  870]]


In [15]:
svm_sigmoid_soft = SVC(kernel='sigmoid', C = 10, max_iter = max_iter)
svm_sigmoid_soft = svm_sigmoid_soft.fit(train_images_flat, train_labels)
y_pred_sigmoid_sof = svm_sigmoid_soft.predict(test_images_flat)
print("Accuracy: ", accuracy_score(test_labels, y_pred_sigmoid_sof))
print("\n\nPrecision:", precision_score(test_labels, y_pred_sigmoid_sof, average="macro"))
print("\n\nRecall:", recall_score(test_labels, y_pred_sigmoid_sof, average="macro"))
print("\n\nConfusion Matrix:\n",confusion_matrix(test_labels, y_pred_sigmoid_sof))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy:  0.5858


Precision: 0.6529153063942926


Recall: 0.5831176376537107


Confusion Matrix:
 [[681   0   7   1   1  76  65   1 139   9]
 [  0 997  35   0   0   2   5   0  96   0]
 [ 38  73 407   3  41  13 140   7 295  15]
 [ 52  15  23  84   5 220  22  18 547  24]
 [  1   5   6   0 717   8  16   7  17 205]
 [ 56  23   8  14  33 352  30   7 322  47]
 [ 25   5  58   1  46  17 778   0  26   2]
 [  5  15  41   3  33   2   1 387  59 482]
 [ 51  37  29   2  27  36  29   6 701  56]
 [ 15   6   2   0 137  11   1  28  55 754]]
